import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, FileText } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/hooks/use-auth";
import { useClients } from "@/hooks/use-data";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export const Route = createFileRoute("/_app/portal/documentos")({ component: ClientDocumentsPortal });
type Doc = { id: string; title: string; description: string | null; file_name: string; storage_path: string; expires_at: string | null; active: boolean };
function ClientDocumentsPortal() { const { data: clients = [] } = useClients(); const { isClient, clientId: linkedClientId } = useAuth(); const [clientId, setClientId] = useState(""); useEffect(() => { if (isClient) setClientId(linkedClientId ?? ""); else if (!clientId && clients[0]) setClientId(clients[0].id); }, [clientId, clients, isClient, linkedClientId]); const { data: documents = [] } = useQuery({ queryKey: ["portal-client-documents", clientId], enabled: !!clientId, queryFn: async () => { const { data, error } = await (supabase.from("client_documents") as any).select("id,title,description,file_name,storage_path,expires_at,active").eq("client_id", clientId).eq("active", true).order("expires_at", { ascending: true, nullsFirst: false }); if (error) throw error; return (data ?? []) as Doc[]; } }); const today = new Date().toISOString().slice(0, 10); const activeDocs = useMemo(() => documents.filter((doc) => !doc.expires_at || doc.expires_at >= today), [documents, today]); const open = async (doc: Doc) => { const { data, error } = await supabase.storage.from("client-documents").createSignedUrl(doc.storage_path, 600); if (error || !data?.signedUrl) return toast.error(error?.message || "Não foi possível abrir o documento."); window.open(data.signedUrl, "_blank", "noopener,noreferrer"); }; const client = clients.find((item) => item.id === clientId); return <div className="mx-auto max-w-5xl space-y-6 p-4 sm:p-6"><header><p className="text-sm font-medium text-primary">Portal do Cliente</p><h1 className="text-2xl font-bold">Documentos</h1><p className="text-sm text-muted-foreground">Documentos vigentes da empresa.</p></header>{!isClient && <Card className="p-4"><Select value={clientId} onValueChange={setClientId}><SelectTrigger className="max-w-md"><SelectValue placeholder="Selecionar cliente" /></SelectTrigger><SelectContent>{clients.map((client) => <SelectItem key={client.id} value={client.id}>{client.name}</SelectItem>)}</SelectContent></Select></Card>}<section className="space-y-3"><h2 className="text-lg font-semibold">{client?.name ?? "Cliente"}</h2>{activeDocs.map((doc) => <Card key={doc.id} className="flex flex-wrap items-center gap-3 p-4"><FileText className="text-primary" /><div className="min-w-0 flex-1"><p className="font-medium">{doc.title}</p><p className="text-sm text-muted-foreground">{doc.description || doc.file_name}{doc.expires_at ? ` · Vigente até ${doc.expires_at}` : ""}</p></div><Button variant="outline" onClick={() => open(doc)}><Download className="mr-2 h-4 w-4" />Abrir</Button></Card>)}{clientId && !activeDocs.length && <Card className="p-10 text-center text-sm text-muted-foreground">Nenhum documento vigente disponível.</Card>}</section></div>; }
