/** Cadastros do cliente alimentam diretamente o demonstrativo mensal. */
import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Download, FilePlus2, Package, Pencil, Scale, Trash2, Truck } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/hooks/use-auth";
import { useClients } from "@/hooks/use-data";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useRouterState } from "@tanstack/react-router";

type Residue={id:string;client_id:string;name:string;waste_class:"class_i"|"class_ii";unit:string;default_rental_rate:number;default_exchange_rate:number;default_treatment_rate:number;active:boolean};
type Equipment={id:string;name:string;equipment_type:string;load_capacity_kg:number|null;plate:string|null;active:boolean};
type Report={id:string;period_start:string;period_end:string;status:"draft"|"published"};
type Movement={id:string;waste_residue_id:string|null;occurred_on:string;placed_quantity:number;removed_quantity:number;weight_kg:number;service_order:string|null;mtr_number:string|null;destination_name:string|null};
type Rate={id:string;waste_residue_id:string|null;rental_rate:number;exchange_rate:number;treatment_rate:number;excluded?:boolean};
type Ticket={id:string;waste_residue_id:string|null;equipment_id:string|null;weighed_on:string|null;ticket_number:string|null;vehicle_plate:string|null;net_weight_kg:number|null};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0); const n=(v:number)=>new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2}).format(v||0); const today=()=>new Date().toISOString().slice(0,10);
const Field=({label,children}:{label:string;children:React.ReactNode})=><div><Label>{label}</Label><div className="mt-1">{children}</div></div>;

export function WasteManagementModule({portal=false}:{portal?:boolean}){
 const qc=useQueryClient(); const {data:clients=[]}=useClients(); const {isAdmin,isClient,clientId:linked}=useAuth(); const [clientId,setClientId]=useState(""); const [reportId,setReportId]=useState(""); const [period,setPeriod]=useState(new Date().toISOString().slice(0,7));
 const search=useRouterState({select:s=>s.location.search}) as {aba?:string}; const catalogTab=search.aba==="residuos"||search.aba==="equipamentos"?search.aba:null; const [view,setView]=useState<string>(catalogTab??"painel"); useEffect(()=>setView(catalogTab??"painel"),[catalogTab]);
 const [resForm,setResForm]=useState({name:"",waste_class:"class_ii",unit:"kg",rental:"0",exchange:"0",treatment:"0"}); const [eqForm,setEqForm]=useState({name:"",type:"",capacity:"",plate:""}); const [move,setMove]=useState({residue:"",date:today(),placed:"0",removed:"0",weight:"0",os:"",mtr:"",destination:""}); const [ticket,setTicket]=useState({residue:"",equipment:"",number:"",date:today(),net:""});
 const [editingResidue,setEditingResidue]=useState<Residue|null>(null); const [editingEquipment,setEditingEquipment]=useState<Equipment|null>(null); const [editingMove,setEditingMove]=useState<Movement|null>(null);
 useEffect(()=>{if(isClient)setClientId(linked??"");else if(!clientId&&clients[0])setClientId(clients[0].id)},[isClient,linked,clientId,clients]);
 const clientQuery=<T,>(key:string,table:string)=>useQuery({queryKey:[key,clientId],enabled:!!clientId,queryFn:async()=>{const {data,error}=await (supabase.from(table as any)as any).select("*").eq("client_id",clientId);if(error)throw error;return(data??[])as T[]}});
 const {data:residues=[]}=clientQuery<Residue>("waste-residues","waste_residues"); const {data:equipment=[]}=clientQuery<Equipment>("waste-equipment","waste_equipment");
 const {data:reports=[]}=useQuery({queryKey:["waste-reports",clientId],enabled:!!clientId,queryFn:async()=>{const {data,error}=await(supabase.from("waste_reports"as any)as any).select("id,period_start,period_end,status").eq("client_id",clientId).order("period_start",{ascending:false});if(error)throw error;return(data??[])as Report[]}}); useEffect(()=>{if(!reportId&&reports[0])setReportId(reports[0].id)},[reports,reportId]); const report=reports.find(r=>r.id===reportId);
 const reportQuery=<T,>(key:string,table:string)=>useQuery({queryKey:[key,reportId],enabled:!!reportId,queryFn:async()=>{const {data,error}=await(supabase.from(table as any)as any).select("*").eq("report_id",reportId);if(error)throw error;return(data??[])as T[]}}); const {data:moves=[]}=reportQuery<Movement>("waste-movements","waste_movements"); const {data:rates=[]}=reportQuery<Rate>("waste-rates","waste_billing_rates"); const {data:tickets=[]}=reportQuery<Ticket>("waste-tickets","waste_weighing_tickets");
 const active=residues.filter(r=>r.active); const activeEq=equipment.filter(e=>e.active); const refreshClient=()=>{void qc.invalidateQueries({queryKey:["waste-residues",clientId]});void qc.invalidateQueries({queryKey:["waste-equipment",clientId]})}; const refreshReport=()=>["waste-movements","waste-rates","waste-tickets"].forEach(key=>void qc.invalidateQueries({queryKey:[key,reportId]}));
 const addResidue=useMutation({mutationFn:async()=>{if(!clientId||!resForm.name)throw Error("Informe o tipo de resíduo.");const payload={client_id:clientId,name:resForm.name,waste_class:resForm.waste_class,unit:resForm.unit,default_rental_rate:Number(resForm.rental),default_exchange_rate:Number(resForm.exchange),default_treatment_rate:Number(resForm.treatment)};const query=(supabase.from("waste_residues"as any)as any);const {error}=editingResidue?await query.update(payload).eq("id",editingResidue.id):await query.insert(payload);if(error)throw error},onSuccess:()=>{toast.success(editingResidue?"Resíduo atualizado.":"Resíduo cadastrado.");setEditingResidue(null);setResForm({name:"",waste_class:"class_ii",unit:"kg",rental:"0",exchange:"0",treatment:"0"});refreshClient()},onError:(e:Error)=>toast.error(e.message)});
 const addEquipment=useMutation({mutationFn:async()=>{if(!clientId||!eqForm.name||!eqForm.type)throw Error("Informe nome e tipo.");const payload={client_id:clientId,name:eqForm.name,equipment_type:eqForm.type,load_capacity_kg:eqForm.capacity?Number(eqForm.capacity):null,plate:eqForm.plate||null};const query=(supabase.from("waste_equipment"as any)as any);const {error}=editingEquipment?await query.update(payload).eq("id",editingEquipment.id):await query.insert(payload);if(error)throw error},onSuccess:()=>{toast.success(editingEquipment?"Equipamento atualizado.":"Equipamento cadastrado.");setEditingEquipment(null);setEqForm({name:"",type:"",capacity:"",plate:""});refreshClient()},onError:(e:Error)=>toast.error(e.message)});
 const createReport=useMutation({mutationFn:async()=>{if(!clientId||!active.length)throw Error("Cadastre pelo menos um resíduo antes.");const[y,m]=period.split("-").map(Number);const {data,error}=await(supabase.from("waste_reports"as any)as any).insert({client_id:clientId,period_start:`${period}-01`,period_end:new Date(y,m,0).toISOString().slice(0,10),status:"draft"}).select("id").single();if(error)throw error;const {error:rateError}=await(supabase.from("waste_billing_rates"as any)as any).insert(active.map(r=>({report_id:data.id,waste_residue_id:r.id,rental_rate:r.default_rental_rate,exchange_rate:r.default_exchange_rate,treatment_rate:r.default_treatment_rate})));if(rateError)throw rateError;return data.id},onSuccess:(id)=>{setReportId(id);void qc.invalidateQueries({queryKey:["waste-reports",clientId]});toast.success("Relatório criado.")},onError:(e:Error)=>toast.error(e.message)});
 const addMove=useMutation({mutationFn:async()=>{if(!reportId||!move.residue)throw Error("Selecione o resíduo.");const payload={report_id:reportId,waste_residue_id:move.residue,occurred_on:move.date,service_order:move.os||null,placed_quantity:Number(move.placed),removed_quantity:Number(move.removed),weight_kg:Number(move.weight),mtr_number:move.mtr||null,destination_name:move.destination||null};const query=(supabase.from("waste_movements"as any)as any);const{error}=editingMove?await query.update(payload).eq("id",editingMove.id):await query.insert(payload);if(error)throw error},onSuccess:()=>{toast.success(editingMove?"Movimentação atualizada.":"Movimentação registrada.");setEditingMove(null);setMove({residue:"",date:today(),placed:"0",removed:"0",weight:"0",os:"",mtr:"",destination:""});refreshReport()},onError:(e:Error)=>toast.error(e.message)});
 const removeRecord=async(table:string,id:string,refresh:()=>void,label:string)=>{if(!window.confirm(`Excluir ${label}?`))return;const{error}=await(supabase.from(table as any)as any).delete().eq("id",id);if(error)toast.error(error.message);else{toast.success(`${label} excluído.`);refresh()}};
 const addTicket=useMutation({mutationFn:async()=>{if(!reportId||!ticket.residue)throw Error("Selecione o resíduo.");const eq=equipment.find(e=>e.id===ticket.equipment);const{error}=await(supabase.from("waste_weighing_tickets"as any)as any).insert({report_id:reportId,waste_residue_id:ticket.residue,equipment_id:ticket.equipment||null,ticket_number:ticket.number||null,weighed_on:ticket.date,vehicle_plate:eq?.plate||null,net_weight_kg:ticket.net?Number(ticket.net):null});if(error)throw error},onSuccess:()=>{toast.success("Ticket registrado.");refreshReport()},onError:(e:Error)=>toast.error(e.message)});
 const rows=useMemo(()=>active.filter(residue=>!rates.find(r=>r.waste_residue_id===residue.id)?.excluded).map(residue=>{const ms=moves.filter(m=>m.waste_residue_id===residue.id);const rate=rates.find(r=>r.waste_residue_id===residue.id);const placed=ms.reduce((s,m)=>s+Number(m.placed_quantity||0)-Number(m.removed_quantity||0),0),exchanges=ms.reduce((s,m)=>s+Number(m.removed_quantity||0),0),weight=ms.reduce((s,m)=>s+Number(m.weight_kg||0),0);const rental=Number(rate?.rental_rate??residue.default_rental_rate),exchange=Number(rate?.exchange_rate??residue.default_exchange_rate),treatment=Number(rate?.treatment_rate??residue.default_treatment_rate);return{residue,placed,exchanges,weight,rental,exchange,treatment,total:placed*rental+exchanges*exchange+weight*treatment}}),[active,moves,rates]); const total=rows.reduce((s,r)=>s+r.total,0); const totalWeight=rows.reduce((s,r)=>s+r.weight,0);
 const saveRate=async(r:typeof rows[number],field:"rental_rate"|"exchange_rate"|"treatment_rate",value:string)=>{const existing=rates.find(x=>x.waste_residue_id===r.residue.id);const{error}=await(supabase.from("waste_billing_rates"as any)as any).upsert({id:existing?.id,report_id:reportId,waste_residue_id:r.residue.id,rental_rate:existing?.rental_rate??r.rental,exchange_rate:existing?.exchange_rate??r.exchange,treatment_rate:existing?.treatment_rate??r.treatment,[field]:Number(value||0)},{onConflict:"report_id,waste_residue_id"});if(error)toast.error(error.message);else refreshReport()};
 const removeFromReport=async(r:typeof rows[number])=>{if(!window.confirm(`Remover ${r.residue.name} somente deste relatório? O cadastro do resíduo será mantido.`))return;const existing=rates.find(x=>x.waste_residue_id===r.residue.id);const{error}=await(supabase.from("waste_billing_rates"as any)as any).upsert({id:existing?.id,report_id:reportId,waste_residue_id:r.residue.id,rental_rate:existing?.rental_rate??r.rental,exchange_rate:existing?.exchange_rate??r.exchange,treatment_rate:existing?.treatment_rate??r.treatment,excluded:true},{onConflict:"report_id,waste_residue_id"});if(error)toast.error(error.message);else{toast.success("Item removido deste relatório.");refreshReport()}};
 const pdf=async()=>{if(!report)return;const{jsPDF}=await import("jspdf");const doc=new jsPDF();doc.setFontSize(18);doc.text("Relatório de Gestão de Resíduos",14,18);doc.setFontSize(10);doc.text(`Período: ${report.period_start} a ${report.period_end}`,14,27);let y=38;rows.forEach(r=>{doc.text(`${r.residue.name}: ${n(r.weight)} kg | ${money(r.total)}`,14,y);y+=7});const max=Math.max(...rows.map(r=>r.weight),1);doc.text("Quantidade destinada por resíduo (kg)",14,y+12);rows.slice(0,8).forEach((r,i)=>{const bar=Math.max(2,(r.weight/max)*130);const by=y+18+i*8;doc.setFillColor(72,126,55);doc.rect(14,by,bar,4,"F");doc.setTextColor(55,70,58);doc.text(`${r.residue.name}: ${n(r.weight)} kg`,148,by+4);});doc.setTextColor(0,0,0);doc.setFontSize(12);doc.text(`Total: ${money(total)}`,14,y+28+Math.min(rows.length,8)*8);doc.save(`residuos-${report.period_start}.pdf`)};
 const pageTitle=catalogTab==="residuos"?"Cadastro de resíduos":catalogTab==="equipamentos"?"Cadastro de equipamentos":"Gestão de Resíduos";
 return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6"><header className="flex justify-between gap-4"><div><p className="text-sm font-medium text-primary">{portal?"Portal do Cliente":"Controle ambiental integrado"}</p><h1 className="text-2xl font-bold">{pageTitle}</h1></div>{!catalogTab&&report&&<Button onClick={()=>void pdf()}><Download className="mr-2 h-4 w-4"/>Gerar PDF</Button>}</header>{catalogTab?<Card className="max-w-xl p-4"><Field label="Cliente">{isClient?<p className="mt-2 font-medium">{clients.find(c=>c.id===clientId)?.name}</p>:<Select value={clientId} onValueChange={v=>{setClientId(v);setReportId("")}}><SelectTrigger><SelectValue placeholder="Cliente"/></SelectTrigger><SelectContent>{clients.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select>}</Field></Card>:<Card className="grid gap-3 p-4 md:grid-cols-4"><Field label="Cliente">{isClient?<p className="mt-2 font-medium">{clients.find(c=>c.id===clientId)?.name}</p>:<Select value={clientId} onValueChange={v=>{setClientId(v);setReportId("")}}><SelectTrigger><SelectValue placeholder="Cliente"/></SelectTrigger><SelectContent>{clients.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select>}</Field><Field label="Relatório"><Select value={reportId} onValueChange={setReportId}><SelectTrigger><SelectValue placeholder="Selecionar"/></SelectTrigger><SelectContent>{reports.map(r=><SelectItem key={r.id} value={r.id}>{r.period_start} · {r.status}</SelectItem>)}</SelectContent></Select></Field>{isAdmin&&<><Field label="Novo período"><Input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></Field><Button className="self-end" onClick={()=>createReport.mutate()}><FilePlus2 className="mr-2 h-4 w-4"/>Novo relatório</Button></>}</Card>}
 <Tabs value={view} onValueChange={setView}>{!catalogTab&&<TabsList className="h-auto w-full justify-start overflow-x-auto"><TabsTrigger value="painel">Painel</TabsTrigger><TabsTrigger value="movimentos">Movimentações</TabsTrigger><TabsTrigger value="faturamento">Demonstrativo de faturamento</TabsTrigger><TabsTrigger value="tickets">Tickets</TabsTrigger></TabsList>}
 <TabsContent value="painel" className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Metric title="Resíduos" value={String(active.length)} icon={<Package/>}/><Metric title="Equipamentos" value={String(activeEq.length)} icon={<Truck/>}/><Metric title="Faturamento" value={money(total)} icon={<Scale/>}/></div><Card className="p-4"><h2 className="font-semibold">Quantidade por resíduo</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows.map(r=>({nome:r.residue.name,kg:r.weight}))}><XAxis dataKey="nome"/><YAxis/><Tooltip/><Bar dataKey="kg" fill="hsl(var(--primary))"/></BarChart></ResponsiveContainer></div></Card></TabsContent>
 <TabsContent value="residuos" className="space-y-4"><Card className="p-4"><h2 className="font-semibold">{editingResidue?"Editar resíduo":"Novo resíduo"}</h2><p className="text-sm text-muted-foreground">O demonstrativo puxa estas categorias e os valores cadastrados.</p><div className="mt-3 grid gap-3 md:grid-cols-3 lg:grid-cols-4"><Field label="Tipo"><Input value={resForm.name} onChange={e=>setResForm({...resForm,name:e.target.value})}/></Field><Field label="Classe"><Select value={resForm.waste_class} onValueChange={v=>setResForm({...resForm,waste_class:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="class_i">Classe I</SelectItem><SelectItem value="class_ii">Classe II</SelectItem></SelectContent></Select></Field><Field label="Locação"><Input type="number" value={resForm.rental} onChange={e=>setResForm({...resForm,rental:e.target.value})}/></Field><Field label="Troca"><Input type="number" value={resForm.exchange} onChange={e=>setResForm({...resForm,exchange:e.target.value})}/></Field><Field label="Tratamento/kg"><Input type="number" value={resForm.treatment} onChange={e=>setResForm({...resForm,treatment:e.target.value})}/></Field><div className="flex gap-2 self-end"><Button onClick={()=>addResidue.mutate()}>{editingResidue?"Salvar":"Cadastrar"}</Button>{editingResidue&&<Button variant="outline" onClick={()=>{setEditingResidue(null);setResForm({name:"",waste_class:"class_ii",unit:"kg",rental:"0",exchange:"0",treatment:"0"})}}>Cancelar</Button>}</div></div></Card><ActionTable headers={["Resíduo","Classe","Locação","Troca","Tratamento","Ações"]} rows={residues.map(r=>[r.name,r.waste_class==="class_i"?"Classe I":"Classe II",money(r.default_rental_rate),money(r.default_exchange_rate),money(r.default_treatment_rate),<div className="flex gap-1"><Button size="icon" variant="ghost" title="Editar" onClick={()=>{setEditingResidue(r);setResForm({name:r.name,waste_class:r.waste_class,unit:r.unit,rental:String(r.default_rental_rate),exchange:String(r.default_exchange_rate),treatment:String(r.default_treatment_rate)})}}><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="ghost" title="Excluir" onClick={()=>void removeRecord("waste_residues",r.id,refreshClient,"resíduo")}><Trash2 className="h-4 w-4 text-destructive"/></Button></div>])}/></TabsContent>
 <TabsContent value="equipamentos" className="space-y-4"><Card className="p-4"><h2 className="font-semibold">{editingEquipment?"Editar equipamento":"Novo equipamento"}</h2><div className="mt-3 grid gap-3 md:grid-cols-3 lg:grid-cols-5"><Field label="Nome"><Input value={eqForm.name} onChange={e=>setEqForm({...eqForm,name:e.target.value})}/></Field><Field label="Tipo"><Input value={eqForm.type} onChange={e=>setEqForm({...eqForm,type:e.target.value})}/></Field><Field label="Capacidade (kg)"><Input type="number" value={eqForm.capacity} onChange={e=>setEqForm({...eqForm,capacity:e.target.value})}/></Field><Field label="Placa"><Input value={eqForm.plate} onChange={e=>setEqForm({...eqForm,plate:e.target.value.toUpperCase()})}/></Field><div className="flex gap-2 self-end"><Button onClick={()=>addEquipment.mutate()}>{editingEquipment?"Salvar":"Cadastrar"}</Button>{editingEquipment&&<Button variant="outline" onClick={()=>{setEditingEquipment(null);setEqForm({name:"",type:"",capacity:"",plate:""})}}>Cancelar</Button>}</div></div></Card><ActionTable headers={["Nome","Tipo","Capacidade","Placa","Ações"]} rows={equipment.map(e=>[e.name,e.equipment_type,e.load_capacity_kg?`${n(e.load_capacity_kg)} kg`:"—",e.plate||"—",<div className="flex gap-1"><Button size="icon" variant="ghost" title="Editar" onClick={()=>{setEditingEquipment(e);setEqForm({name:e.name,type:e.equipment_type,capacity:e.load_capacity_kg===null?"":String(e.load_capacity_kg),plate:e.plate||""})}}><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="ghost" title="Excluir" onClick={()=>void removeRecord("waste_equipment",e.id,refreshClient,"equipamento")}><Trash2 className="h-4 w-4 text-destructive"/></Button></div>])}/></TabsContent>
 <TabsContent value="movimentos" className="space-y-4">{isAdmin&&<Card className="p-4"><h2 className="font-semibold">{editingMove?"Editar movimentação":"Nova movimentação"}</h2><div className="mt-3 grid gap-3 md:grid-cols-3 lg:grid-cols-4"><Field label="Resíduo"><ResidueSelect residues={active} value={move.residue} onChange={v=>setMove({...move,residue:v})}/></Field><Field label="Data"><Input type="date" value={move.date} onChange={e=>setMove({...move,date:e.target.value})}/></Field><Field label="Peso kg"><Input type="number" value={move.weight} onChange={e=>setMove({...move,weight:e.target.value})}/></Field><Field label="Colocados"><Input type="number" value={move.placed} onChange={e=>setMove({...move,placed:e.target.value})}/></Field><Field label="Trocas"><Input type="number" value={move.removed} onChange={e=>setMove({...move,removed:e.target.value})}/></Field><Field label="MTR"><Input value={move.mtr} onChange={e=>setMove({...move,mtr:e.target.value})}/></Field><Field label="Destinação"><Input value={move.destination} onChange={e=>setMove({...move,destination:e.target.value})}/></Field><div className="flex gap-2 self-end"><Button onClick={()=>addMove.mutate()}>{editingMove?"Salvar":"Registrar"}</Button>{editingMove&&<Button variant="outline" onClick={()=>{setEditingMove(null);setMove({residue:"",date:today(),placed:"0",removed:"0",weight:"0",os:"",mtr:"",destination:""})}}>Cancelar</Button>}</div></div></Card>}<ActionTable headers={["Data","Resíduo","Peso","Trocas","MTR","Ações"]} rows={moves.map(m=>[m.occurred_on,residues.find(r=>r.id===m.waste_residue_id)?.name||"—",`${n(m.weight_kg)} kg`,n(m.removed_quantity),m.mtr_number||"—",isAdmin?<div className="flex gap-1"><Button size="icon" variant="ghost" title="Editar" onClick={()=>{setEditingMove(m);setMove({residue:m.waste_residue_id||"",date:m.occurred_on,placed:String(m.placed_quantity||0),removed:String(m.removed_quantity||0),weight:String(m.weight_kg||0),os:m.service_order||"",mtr:m.mtr_number||"",destination:m.destination_name||""})}}><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="ghost" title="Excluir" onClick={()=>void removeRecord("waste_movements",m.id,refreshReport,"movimentação")}><Trash2 className="h-4 w-4 text-destructive"/></Button></div>:"—"])}/></TabsContent>
 <TabsContent value="faturamento"><Tabs defaultValue="locacao"><TabsList><TabsTrigger value="locacao">Valor da locação</TabsTrigger><TabsTrigger value="troca">Valor da troca</TabsTrigger><TabsTrigger value="tratamento">Tratamento</TabsTrigger><TabsTrigger value="total">Total</TabsTrigger></TabsList>{([['locacao','rental_rate','Locação'] as const,['troca','exchange_rate','Troca'] as const,['tratamento','treatment_rate','Tratamento/kg'] as const]).map(([tab,field,label])=><TabsContent key={tab} value={tab}><BillingTable rows={rows} label={label} field={field} admin={isAdmin} save={saveRate} remove={removeFromReport}/></TabsContent>)}<TabsContent value="total"><SimpleTable headers={["Resíduo","Locação","Troca","Tratamento","Total"]} rows={rows.map(r=>[r.residue.name,money(r.placed*r.rental),money(r.exchanges*r.exchange),money(r.weight*r.treatment),money(r.total)])}/><Card className="p-4 text-right font-bold">Total geral: {money(total)}</Card></TabsContent></Tabs></TabsContent>
 <TabsContent value="tickets" className="space-y-4">{isAdmin&&<Card className="p-4"><h2 className="font-semibold">Novo ticket</h2><div className="mt-3 grid gap-3 md:grid-cols-3 lg:grid-cols-4"><Field label="Resíduo"><ResidueSelect residues={active} value={ticket.residue} onChange={v=>setTicket({...ticket,residue:v})}/></Field><Field label="Equipamento"><Select value={ticket.equipment} onValueChange={v=>setTicket({...ticket,equipment:v})}><SelectTrigger><SelectValue placeholder="Selecionar"/></SelectTrigger><SelectContent>{activeEq.map(e=><SelectItem key={e.id} value={e.id}>{e.name}{e.plate?` · ${e.plate}`:""}</SelectItem>)}</SelectContent></Select></Field><Field label="Data"><Input type="date" value={ticket.date} onChange={e=>setTicket({...ticket,date:e.target.value})}/></Field><Field label="Peso líquido"><Input type="number" value={ticket.net} onChange={e=>setTicket({...ticket,net:e.target.value})}/></Field><Button className="self-end" onClick={()=>addTicket.mutate()}>Registrar</Button></div></Card>}<SimpleTable headers={["Data","Resíduo","Equipamento","Placa","Peso"]} rows={tickets.map(t=>[t.weighed_on||"—",residues.find(r=>r.id===t.waste_residue_id)?.name||"—",equipment.find(e=>e.id===t.equipment_id)?.name||"—",t.vehicle_plate||"—",`${n(Number(t.net_weight_kg||0))} kg`])}/></TabsContent></Tabs></div>
}
function Metric({title,value,icon}:{title:string;value:string;icon:React.ReactNode}){return <Card className="p-4"><div className="flex justify-between text-muted-foreground"><span>{title}</span>{icon}</div><strong className="mt-2 block text-xl">{value}</strong></Card>}
function ResidueSelect({residues,value,onChange}:{residues:Residue[];value:string;onChange:(v:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue placeholder="Selecionar"/></SelectTrigger><SelectContent>{residues.map(r=><SelectItem key={r.id} value={r.id}>{r.name}</SelectItem>)}</SelectContent></Select>}
function SimpleTable({headers,rows}:{headers:string[];rows:string[][]}){return <Card className="overflow-x-auto p-4"><table className="min-w-[650px] w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground">{headers.map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-b">{row.map((cell,j)=><td key={j} className="p-2">{cell}</td>)}</tr>)}{!rows.length&&<tr><td className="p-8 text-center text-muted-foreground" colSpan={headers.length}>Nenhum registro.</td></tr>}</tbody></table></Card>}
function ActionTable({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <Card className="overflow-x-auto p-4"><table className="min-w-[650px] w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground">{headers.map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-b">{row.map((cell,j)=><td key={j} className="p-2">{cell}</td>)}</tr>)}{!rows.length&&<tr><td className="p-8 text-center text-muted-foreground" colSpan={headers.length}>Nenhum registro.</td></tr>}</tbody></table></Card>}
function BillingTable({rows,label,field,admin,save,remove}:{rows:any[];label:string;field:"rental_rate"|"exchange_rate"|"treatment_rate";admin:boolean;save:(r:any,f:any,v:string)=>Promise<void>;remove:(r:any)=>Promise<void>}){const qty=(r:any)=>field==="rental_rate"?r.placed:field==="exchange_rate"?r.exchanges:r.weight;const rate=(r:any)=>field==="rental_rate"?r.rental:field==="exchange_rate"?r.exchange:r.treatment;return <Card className="overflow-x-auto p-4"><table className="min-w-[650px] w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-2">Resíduo</th><th className="p-2">{field==="treatment_rate"?"Peso (kg)":"Quantidade"}</th><th className="p-2">{label}</th><th className="p-2">Subtotal</th>{admin&&<th className="p-2">Ações</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.residue.id} className="border-b"><td className="p-2 font-medium">{r.residue.name}</td><td className="p-2">{n(qty(r))}</td><td className="p-2">{admin?<Input className="h-8 max-w-32" type="number" min="0" step="0.01" defaultValue={rate(r)} onBlur={e=>void save(r,field,e.target.value)}/>:money(rate(r))}</td><td className="p-2">{money(qty(r)*rate(r))}</td>{admin&&<td className="p-2"><Button size="icon" variant="ghost" title="Remover deste relatório" onClick={()=>void remove(r)}><Trash2 className="h-4 w-4 text-destructive"/></Button></td>}</tr>)}{!rows.length&&<tr><td className="p-8 text-center text-muted-foreground" colSpan={admin?5:4}>Nenhum resíduo incluído neste relatório.</td></tr>}</tbody></table>{admin&&<p className="mt-3 text-xs text-muted-foreground">Altere o valor no campo ou use a lixeira para remover o item somente deste relatório.</p>}</Card>}
