/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppArquivosRouteImport } from './routes/_app/arquivos'
import { Route as AppCalendarioRouteImport } from './routes/_app/calendario'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppImportAtaRouteImport } from './routes/_app/import-ata'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppResiduosRouteImport } from './routes/_app/residuos'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppTerceirizadosRouteImport } from './routes/_app/terceirizados'
import { Route as AppTrashRouteImport } from './routes/_app/trash'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as ApiOnedriveRouteImport } from './routes/api/onedrive'
import { Route as AppClientReportClientIdRouteImport } from './routes/_app/client-report.$clientId'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients.index'
import { Route as AppClientsNewRouteImport } from './routes/_app/clients.new'
import { Route as AppPortalContaRouteImport } from './routes/_app/portal.conta'
import { Route as AppPortalDocumentosRouteImport } from './routes/_app/portal.documentos'
import { Route as AppPortalEntregasRouteImport } from './routes/_app/portal.entregas'
import { Route as AppPortalFinanceiroRouteImport } from './routes/_app/portal.financeiro'
import { Route as AppPortalMovimentacoesRouteImport } from './routes/_app/portal.movimentacoes'
import { Route as AppPortalResiduosRouteImport } from './routes/_app/portal.residuos'
import { Route as AppPortalUnidadesRouteImport } from './routes/_app/portal.unidades'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks.index'
import { Route as AppTasksCalendarRouteImport } from './routes/_app/tasks.calendar'
import { Route as AppTasksKanbanRouteImport } from './routes/_app/tasks.kanban'
import { Route as AppTasksListRouteImport } from './routes/_app/tasks.list'
import { Route as ApiOnedriveCallbackRouteImport } from './routes/api/onedrive.callback'
import { Route as AppClientsClientIdEditRouteImport } from './routes/_app/clients.$clientId.edit'
import { Route as ApiOnedriveContentItemIdRouteImport } from './routes/api/onedrive.content.$itemId'
import { Route as ApiOnedriveDownloadItemIdRouteImport } from './routes/api/onedrive.download.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppArquivosRoute = AppArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppImportAtaRoute = AppImportAtaRouteImport.update({
  id: '/import-ata',
  path: '/import-ata',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppResiduosRoute = AppResiduosRouteImport.update({
  id: '/residuos',
  path: '/residuos',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTerceirizadosRoute = AppTerceirizadosRouteImport.update({
  id: '/terceirizados',
  path: '/terceirizados',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const ApiOnedriveRoute = ApiOnedriveRouteImport.update({
  id: '/api/onedrive',
  path: '/api/onedrive',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientReportClientIdRoute = AppClientReportClientIdRouteImport.update({
  id: '/client-report/$clientId',
  path: '/client-report/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppPortalContaRoute = AppPortalContaRouteImport.update({
  id: '/portal/conta',
  path: '/portal/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalDocumentosRoute = AppPortalDocumentosRouteImport.update({
  id: '/portal/documentos',
  path: '/portal/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalEntregasRoute = AppPortalEntregasRouteImport.update({
  id: '/portal/entregas',
  path: '/portal/entregas',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalFinanceiroRoute = AppPortalFinanceiroRouteImport.update({
  id: '/portal/financeiro',
  path: '/portal/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalMovimentacoesRoute = AppPortalMovimentacoesRouteImport.update({
  id: '/portal/movimentacoes',
  path: '/portal/movimentacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalResiduosRoute = AppPortalResiduosRouteImport.update({
  id: '/portal/residuos',
  path: '/portal/residuos',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalUnidadesRoute = AppPortalUnidadesRouteImport.update({
  id: '/portal/unidades',
  path: '/portal/unidades',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksCalendarRoute = AppTasksCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksKanbanRoute = AppTasksKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksListRoute = AppTasksListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppTasksRoute,
} as any)
const ApiOnedriveCallbackRoute = ApiOnedriveCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiOnedriveRoute,
} as any)
const AppClientsClientIdEditRoute = AppClientsClientIdEditRouteImport.update({
  id: '/$clientId/edit',
  path: '/$clientId/edit',
  getParentRoute: () => AppClientsRoute,
} as any)
const ApiOnedriveContentItemIdRoute =
  ApiOnedriveContentItemIdRouteImport.update({
    id: '/content/$itemId',
    path: '/content/$itemId',
    getParentRoute: () => ApiOnedriveRoute,
  } as any)
const ApiOnedriveDownloadItemIdRoute =
  ApiOnedriveDownloadItemIdRouteImport.update({
    id: '/download/$itemId',
    path: '/download/$itemId',
    getParentRoute: () => ApiOnedriveRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arquivos': typeof AppArquivosRoute
  '/calendario': typeof AppCalendarioRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/import-ata': typeof AppImportAtaRoute
  '/notes': typeof AppNotesRoute
  '/reports': typeof AppReportsRoute
  '/residuos': typeof AppResiduosRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/terceirizados': typeof AppTerceirizadosRoute
  '/trash': typeof AppTrashRoute
  '/users': typeof AppUsersRoute
  '/api/onedrive': typeof ApiOnedriveRouteWithChildren
  '/client-report/$clientId': typeof AppClientReportClientIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/portal/conta': typeof AppPortalContaRoute
  '/portal/documentos': typeof AppPortalDocumentosRoute
  '/portal/entregas': typeof AppPortalEntregasRoute
  '/portal/financeiro': typeof AppPortalFinanceiroRoute
  '/portal/movimentacoes': typeof AppPortalMovimentacoesRoute
  '/portal/residuos': typeof AppPortalResiduosRoute
  '/portal/unidades': typeof AppPortalUnidadesRoute
  '/tasks/calendar': typeof AppTasksCalendarRoute
  '/tasks/kanban': typeof AppTasksKanbanRoute
  '/tasks/list': typeof AppTasksListRoute
  '/api/onedrive/callback': typeof ApiOnedriveCallbackRoute
  '/clients/': typeof AppClientsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/clients/$clientId/edit': typeof AppClientsClientIdEditRoute
  '/api/onedrive/content/$itemId': typeof ApiOnedriveContentItemIdRoute
  '/api/onedrive/download/$itemId': typeof ApiOnedriveDownloadItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arquivos': typeof AppArquivosRoute
  '/calendario': typeof AppCalendarioRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/import-ata': typeof AppImportAtaRoute
  '/notes': typeof AppNotesRoute
  '/reports': typeof AppReportsRoute
  '/residuos': typeof AppResiduosRoute
  '/settings': typeof AppSettingsRoute
  '/terceirizados': typeof AppTerceirizadosRoute
  '/trash': typeof AppTrashRoute
  '/users': typeof AppUsersRoute
  '/api/onedrive': typeof ApiOnedriveRouteWithChildren
  '/client-report/$clientId': typeof AppClientReportClientIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/portal/conta': typeof AppPortalContaRoute
  '/portal/documentos': typeof AppPortalDocumentosRoute
  '/portal/entregas': typeof AppPortalEntregasRoute
  '/portal/financeiro': typeof AppPortalFinanceiroRoute
  '/portal/movimentacoes': typeof AppPortalMovimentacoesRoute
  '/portal/residuos': typeof AppPortalResiduosRoute
  '/portal/unidades': typeof AppPortalUnidadesRoute
  '/tasks/calendar': typeof AppTasksCalendarRoute
  '/tasks/kanban': typeof AppTasksKanbanRoute
  '/tasks/list': typeof AppTasksListRoute
  '/api/onedrive/callback': typeof ApiOnedriveCallbackRoute
  '/clients': typeof AppClientsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/clients/$clientId/edit': typeof AppClientsClientIdEditRoute
  '/api/onedrive/content/$itemId': typeof ApiOnedriveContentItemIdRoute
  '/api/onedrive/download/$itemId': typeof ApiOnedriveDownloadItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/arquivos': typeof AppArquivosRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/import-ata': typeof AppImportAtaRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/residuos': typeof AppResiduosRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/_app/terceirizados': typeof AppTerceirizadosRoute
  '/_app/trash': typeof AppTrashRoute
  '/_app/users': typeof AppUsersRoute
  '/api/onedrive': typeof ApiOnedriveRouteWithChildren
  '/_app/client-report/$clientId': typeof AppClientReportClientIdRoute
  '/_app/clients/new': typeof AppClientsNewRoute
  '/_app/portal/conta': typeof AppPortalContaRoute
  '/_app/portal/documentos': typeof AppPortalDocumentosRoute
  '/_app/portal/entregas': typeof AppPortalEntregasRoute
  '/_app/portal/financeiro': typeof AppPortalFinanceiroRoute
  '/_app/portal/movimentacoes': typeof AppPortalMovimentacoesRoute
  '/_app/portal/residuos': typeof AppPortalResiduosRoute
  '/_app/portal/unidades': typeof AppPortalUnidadesRoute
  '/_app/tasks/calendar': typeof AppTasksCalendarRoute
  '/_app/tasks/kanban': typeof AppTasksKanbanRoute
  '/_app/tasks/list': typeof AppTasksListRoute
  '/api/onedrive/callback': typeof ApiOnedriveCallbackRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/clients/$clientId/edit': typeof AppClientsClientIdEditRoute
  '/api/onedrive/content/$itemId': typeof ApiOnedriveContentItemIdRoute
  '/api/onedrive/download/$itemId': typeof ApiOnedriveDownloadItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/arquivos'
    | '/calendario'
    | '/clients'
    | '/dashboard'
    | '/financeiro'
    | '/import-ata'
    | '/notes'
    | '/reports'
    | '/residuos'
    | '/settings'
    | '/tasks'
    | '/terceirizados'
    | '/trash'
    | '/users'
    | '/api/onedrive'
    | '/client-report/$clientId'
    | '/clients/new'
    | '/portal/conta'
    | '/portal/documentos'
    | '/portal/entregas'
    | '/portal/financeiro'
    | '/portal/movimentacoes'
    | '/portal/residuos'
    | '/portal/unidades'
    | '/tasks/calendar'
    | '/tasks/kanban'
    | '/tasks/list'
    | '/api/onedrive/callback'
    | '/clients/'
    | '/tasks/'
    | '/clients/$clientId/edit'
    | '/api/onedrive/content/$itemId'
    | '/api/onedrive/download/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/arquivos'
    | '/calendario'
    | '/dashboard'
    | '/financeiro'
    | '/import-ata'
    | '/notes'
    | '/reports'
    | '/residuos'
    | '/settings'
    | '/terceirizados'
    | '/trash'
    | '/users'
    | '/api/onedrive'
    | '/client-report/$clientId'
    | '/clients/new'
    | '/portal/conta'
    | '/portal/documentos'
    | '/portal/entregas'
    | '/portal/financeiro'
    | '/portal/movimentacoes'
    | '/portal/residuos'
    | '/portal/unidades'
    | '/tasks/calendar'
    | '/tasks/kanban'
    | '/tasks/list'
    | '/api/onedrive/callback'
    | '/clients'
    | '/tasks'
    | '/clients/$clientId/edit'
    | '/api/onedrive/content/$itemId'
    | '/api/onedrive/download/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/arquivos'
    | '/_app/calendario'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/financeiro'
    | '/_app/import-ata'
    | '/_app/notes'
    | '/_app/reports'
    | '/_app/residuos'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/terceirizados'
    | '/_app/trash'
    | '/_app/users'
    | '/api/onedrive'
    | '/_app/client-report/$clientId'
    | '/_app/clients/new'
    | '/_app/portal/conta'
    | '/_app/portal/documentos'
    | '/_app/portal/entregas'
    | '/_app/portal/financeiro'
    | '/_app/portal/movimentacoes'
    | '/_app/portal/residuos'
    | '/_app/portal/unidades'
    | '/_app/tasks/calendar'
    | '/_app/tasks/kanban'
    | '/_app/tasks/list'
    | '/api/onedrive/callback'
    | '/_app/clients/'
    | '/_app/tasks/'
    | '/_app/clients/$clientId/edit'
    | '/api/onedrive/content/$itemId'
    | '/api/onedrive/download/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiOnedriveRoute: typeof ApiOnedriveRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/arquivos': {
      id: '/_app/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AppArquivosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-ata': {
      id: '/_app/import-ata'
      path: '/import-ata'
      fullPath: '/import-ata'
      preLoaderRoute: typeof AppImportAtaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/residuos': {
      id: '/_app/residuos'
      path: '/residuos'
      fullPath: '/residuos'
      preLoaderRoute: typeof AppResiduosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terceirizados': {
      id: '/_app/terceirizados'
      path: '/terceirizados'
      fullPath: '/terceirizados'
      preLoaderRoute: typeof AppTerceirizadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/onedrive': {
      id: '/api/onedrive'
      path: '/api/onedrive'
      fullPath: '/api/onedrive'
      preLoaderRoute: typeof ApiOnedriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/client-report/$clientId': {
      id: '/_app/client-report/$clientId'
      path: '/client-report/$clientId'
      fullPath: '/client-report/$clientId'
      preLoaderRoute: typeof AppClientReportClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/clients/new': {
      id: '/_app/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/portal/conta': {
      id: '/_app/portal/conta'
      path: '/portal/conta'
      fullPath: '/portal/conta'
      preLoaderRoute: typeof AppPortalContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/documentos': {
      id: '/_app/portal/documentos'
      path: '/portal/documentos'
      fullPath: '/portal/documentos'
      preLoaderRoute: typeof AppPortalDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/entregas': {
      id: '/_app/portal/entregas'
      path: '/portal/entregas'
      fullPath: '/portal/entregas'
      preLoaderRoute: typeof AppPortalEntregasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/financeiro': {
      id: '/_app/portal/financeiro'
      path: '/portal/financeiro'
      fullPath: '/portal/financeiro'
      preLoaderRoute: typeof AppPortalFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/movimentacoes': {
      id: '/_app/portal/movimentacoes'
      path: '/portal/movimentacoes'
      fullPath: '/portal/movimentacoes'
      preLoaderRoute: typeof AppPortalMovimentacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/residuos': {
      id: '/_app/portal/residuos'
      path: '/portal/residuos'
      fullPath: '/portal/residuos'
      preLoaderRoute: typeof AppPortalResiduosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/unidades': {
      id: '/_app/portal/unidades'
      path: '/portal/unidades'
      fullPath: '/portal/unidades'
      preLoaderRoute: typeof AppPortalUnidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/tasks/calendar': {
      id: '/_app/tasks/calendar'
      path: '/calendar'
      fullPath: '/tasks/calendar'
      preLoaderRoute: typeof AppTasksCalendarRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/tasks/kanban': {
      id: '/_app/tasks/kanban'
      path: '/kanban'
      fullPath: '/tasks/kanban'
      preLoaderRoute: typeof AppTasksKanbanRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/tasks/list': {
      id: '/_app/tasks/list'
      path: '/list'
      fullPath: '/tasks/list'
      preLoaderRoute: typeof AppTasksListRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/api/onedrive/callback': {
      id: '/api/onedrive/callback'
      path: '/callback'
      fullPath: '/api/onedrive/callback'
      preLoaderRoute: typeof ApiOnedriveCallbackRouteImport
      parentRoute: typeof ApiOnedriveRoute
    }
    '/_app/clients/$clientId/edit': {
      id: '/_app/clients/$clientId/edit'
      path: '/$clientId/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AppClientsClientIdEditRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/api/onedrive/content/$itemId': {
      id: '/api/onedrive/content/$itemId'
      path: '/content/$itemId'
      fullPath: '/api/onedrive/content/$itemId'
      preLoaderRoute: typeof ApiOnedriveContentItemIdRouteImport
      parentRoute: typeof ApiOnedriveRoute
    }
    '/api/onedrive/download/$itemId': {
      id: '/api/onedrive/download/$itemId'
      path: '/download/$itemId'
      fullPath: '/api/onedrive/download/$itemId'
      preLoaderRoute: typeof ApiOnedriveDownloadItemIdRouteImport
      parentRoute: typeof ApiOnedriveRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppClientsClientIdEditRoute: typeof AppClientsClientIdEditRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsNewRoute: AppClientsNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppClientsClientIdEditRoute: AppClientsClientIdEditRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppTasksRouteChildren {
  AppTasksCalendarRoute: typeof AppTasksCalendarRoute
  AppTasksKanbanRoute: typeof AppTasksKanbanRoute
  AppTasksListRoute: typeof AppTasksListRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksCalendarRoute: AppTasksCalendarRoute,
  AppTasksKanbanRoute: AppTasksKanbanRoute,
  AppTasksListRoute: AppTasksListRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppRouteChildren {
  AppArquivosRoute: typeof AppArquivosRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppImportAtaRoute: typeof AppImportAtaRoute
  AppNotesRoute: typeof AppNotesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResiduosRoute: typeof AppResiduosRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppTerceirizadosRoute: typeof AppTerceirizadosRoute
  AppTrashRoute: typeof AppTrashRoute
  AppUsersRoute: typeof AppUsersRoute
  AppClientReportClientIdRoute: typeof AppClientReportClientIdRoute
  AppPortalContaRoute: typeof AppPortalContaRoute
  AppPortalDocumentosRoute: typeof AppPortalDocumentosRoute
  AppPortalEntregasRoute: typeof AppPortalEntregasRoute
  AppPortalFinanceiroRoute: typeof AppPortalFinanceiroRoute
  AppPortalMovimentacoesRoute: typeof AppPortalMovimentacoesRoute
  AppPortalResiduosRoute: typeof AppPortalResiduosRoute
  AppPortalUnidadesRoute: typeof AppPortalUnidadesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArquivosRoute: AppArquivosRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppImportAtaRoute: AppImportAtaRoute,
  AppNotesRoute: AppNotesRoute,
  AppReportsRoute: AppReportsRoute,
  AppResiduosRoute: AppResiduosRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppTerceirizadosRoute: AppTerceirizadosRoute,
  AppTrashRoute: AppTrashRoute,
  AppUsersRoute: AppUsersRoute,
  AppClientReportClientIdRoute: AppClientReportClientIdRoute,
  AppPortalContaRoute: AppPortalContaRoute,
  AppPortalDocumentosRoute: AppPortalDocumentosRoute,
  AppPortalEntregasRoute: AppPortalEntregasRoute,
  AppPortalFinanceiroRoute: AppPortalFinanceiroRoute,
  AppPortalMovimentacoesRoute: AppPortalMovimentacoesRoute,
  AppPortalResiduosRoute: AppPortalResiduosRoute,
  AppPortalUnidadesRoute: AppPortalUnidadesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiOnedriveRouteChildren {
  ApiOnedriveCallbackRoute: typeof ApiOnedriveCallbackRoute
  ApiOnedriveContentItemIdRoute: typeof ApiOnedriveContentItemIdRoute
  ApiOnedriveDownloadItemIdRoute: typeof ApiOnedriveDownloadItemIdRoute
}

const ApiOnedriveRouteChildren: ApiOnedriveRouteChildren = {
  ApiOnedriveCallbackRoute: ApiOnedriveCallbackRoute,
  ApiOnedriveContentItemIdRoute: ApiOnedriveContentItemIdRoute,
  ApiOnedriveDownloadItemIdRoute: ApiOnedriveDownloadItemIdRoute,
}

const ApiOnedriveRouteWithChildren = ApiOnedriveRoute._addFileChildren(
  ApiOnedriveRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiOnedriveRoute: ApiOnedriveRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
